/**
 * Contador Playbacks API
 * API para la app contador-playbacks
 *
 * OpenAPI spec version: 1.0.0
 * Contact: transformaciondigital@hogueras.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import {
    HttpClient,
    HttpEvent,
    HttpHeaders,
    HttpResponse
} from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';

import { Observable } from 'rxjs';

import { InlineResponse200 } from '../model/inlineResponse200';
import { Session } from '../model/session';
import { SessionResponse } from '../model/sessionResponse';
import { SessionsResponse } from '../model/sessionsResponse';

import { Configuration } from '../configuration';
import { BASE_PATH } from '../variables';


@Injectable({ providedIn: 'root' })
export class SesionesService {

    protected basePath = 'https://virtserver.swaggerhub.com/federaciodefogueres/contador-playbacks-api/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Crea una sesión
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSesion(body?: Session, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public createSesion(body?: Session, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public createSesion(body?: Session, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public createSesion(body?: Session, observe: any = 'body', reportProgress: boolean = false): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<InlineResponse200>('post', `${this.basePath}/sesiones`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Borra los datos de la sesión pasada por parámetro.
     * @param idSession 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSesion(idSession: string, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public deleteSesion(idSession: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public deleteSesion(idSession: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public deleteSesion(idSession: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (idSession === null || idSession === undefined) {
            throw new Error('Required parameter idSession was null or undefined when calling deleteSesion.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<InlineResponse200>('delete', `${this.basePath}/sesiones/${encodeURIComponent(String(idSession))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Devuelve todas las sesiones con su información.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllSessions(observe?: 'body', reportProgress?: boolean): Observable<SessionsResponse>;
    public getAllSessions(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SessionsResponse>>;
    public getAllSessions(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SessionsResponse>>;
    public getAllSessions(observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SessionsResponse>('get', `${this.basePath}/sesiones`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Devuelve la información de la sesión solicitada.
     * @param idSession 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSession(idSession: string, observe?: 'body', reportProgress?: boolean): Observable<SessionResponse>;
    public getSession(idSession: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SessionResponse>>;
    public getSession(idSession: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SessionResponse>>;
    public getSession(idSession: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (idSession === null || idSession === undefined) {
            throw new Error('Required parameter idSession was null or undefined when calling getSession.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SessionResponse>('get', `${this.basePath}/sesiones/${encodeURIComponent(String(idSession))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Actualizar una sesión
     * @param idSession 
     * @param body Item to add
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putSesion(idSession: string, body?: Session, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public putSesion(idSession: string, body?: Session, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public putSesion(idSession: string, body?: Session, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public putSesion(idSession: string, body?: Session, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (idSession === null || idSession === undefined) {
            throw new Error('Required parameter idSession was null or undefined when calling putSesion.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<InlineResponse200>('put', `${this.basePath}/sesiones/${encodeURIComponent(String(idSession))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
